{
  "services": {
    "bot": {
      "network_mode": "host"
    },
    "api": {
      "volumes": [
        "./static/uploads:/app/static/uploads",
        "./static/document:/app/static/document"
      ]
    }
  }
}
